services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tp_monolith
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_pass
    ports: ["5432:5432"]
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql
      - ./db/seed_bad_terms.sql:/docker-entrypoint-initdb.d/01_seed_bad_terms.sql
      - ./db/seed_texts.sql:/docker-entrypoint-initdb.d/02_seed_texts.sql

  app:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: tp_monolith
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_pass
    depends_on: [db]
    ports: ["8080:8080"]

